services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=chatapp
    ports:
      - 8081:8081
    expose:
      - 8081
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
    networks:
      - backend
networks:
  backend:
    driver: bridge
